openapi: 3.0.0
servers:
  - url: //petstore.swagger.io/v2
    description: Default server
  - url: //petstore.swagger.io/sandbox
    description: Sandbox server
info:
  description: |

    # Introduction
    This documentation is intended to be used as manual to use for SPIN API Payment.
    In this document will explain in details how to use the API with SPIN and what are the best practices.

    # URL For API Call
    There are only 3 available API’s that can be used with spin merchants. The API’s are used to either to
    begin the transaction flow by obtaining the token, kick off a new payment by passing the payment
    parameters or to check the status of an existing payment. 

    Get the token used based on the user’s api-key and api-secret:
      - PROD - https://open-api-web.spinpay.id/v1/api/payment/get-token
      - DEV - https://dev-open-api-web-1.spinpay.id/v1/api/payment/get-token
    
    Begin the payment process flow:
      - PROD - https://open-api-web.spinpay.id/v1/api/payment/do-payment
      - DEV - https://dev-open-api-web-1.spinpay.id/v1/api/payment/do-payment
    
    Will check the payment status of a given payment provided the payment session id:
      - PROD - https://open-api-web.spinpay.id/v1/api/payment/check-payment
      - DEV - https://dev-open-api-web-1.spinpay.id/v1/api/payment/check-payment
    
    Will reverse the payment provided the payment session id:
      - PROD - https://open-api-web.spinpay.id/v1/api/payment/reverse-payment
      - DEV - https://dev-open-api-web-1.spinpay.id/v1/api/payment/reverse-payment

    # Authentication
    The API need to be authenticated using api-key and api-secret. You can get the key and secret from SPIN Integration Team.
    There will be 2 key and secret, 1 will be use in development and 1 will be use in production. 

    Example Development Key and Secret
      - dev_my_store_key
      - dev_secret_abcdefghjiklmnopqrstuvwxyz
    
    Example Production Key
      - my_store_key
      - secret_abcdefghjiklmnopqrstuvwxyz

  version: 1.0.0
  title: Payment Channel API Documentation
  termsOfService: 'http://swagger.io/terms/'
  contact:
    name: API Support
    email: apiteam@swagger.io
    url: https://github.com/Redocly/redoc
  x-logo:
    url: 'https://i1.wp.com/goodmoney.id/wp-content/uploads/2019/10/spin.jpeg?fit=586%2C381&ssl=1'
    altText: Spin logo
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
externalDocs:
  description: Find out how to create Github repo for your OpenAPI spec.
  url: 'https://github.com/Rebilly/generator-openapi-repo'
tags:
  - name: Web Payment SPIN
    description: The purpose of this document is to highlight how to connect to SPIN as a payment channel
paths:
  /v1/api/payment/get-token:
    post:
      tags:
        - Web Payment SPIN
      summary: Get token to process payment
      requestBody:
        description : Before you process a web payment, you have to get a token first from SPIN using HTTP POST. The body in JSON and the response will be in JSON.
        required: true
        content: 
            application/json:
                schema:
                    $ref: '#/components/schemas/RequestToken'
      produces: application/json
      responses:
        '200':
          description: OK
          content:
            success/json:
              schema:
                $ref: '#/components/schemas/ResponsToken'
            failed/json:
              schema:
                $ref: '#/components/schemas/ResponsTokenFailed'
        '500':
          description: Internal Server Error
  /v1/api/payment/do-payment:
    post:
      tags:
        - Web Payment SPIN
      summary: Process payment
      parameters: 
        - name: auth-key
          in: header
          required: true
          description: api-key value
          type: string
          example: dev_my_store_key
        - name: auth-token
          in: header
          required: true
          description: sha256(“||%%||” + api-key +“||%%||” amount + wallet_id + mid + invoice_code + merchant_callback “||%%||” +api_gen_token +“||%%||”)
          type: string
          example: auth_token_abcdefghjiklmnopqrstuvwxyz1234567890
      requestBody:
        description : process data to get the Payment URL
        required: true
        content: 
            application/json:
                schema:
                    $ref: '#/components/schemas/RequestDoPayment'
      produces: application/json
      responses:
        '200':
          description: OK
          content:
            success/json:
              schema:
                $ref: '#/components/schemas/ResponsDoPayment'
            success/html:
              schema:
                type: string
              examples:
                response:
                  value:  <html><script>window.location.replace("https://dev-open-api-web-1.spinpay.id/console/view-payment-option?pay_session_trx=TRX_15868008551055_4857808_2225864_9021745&one_time_token=91b1d82cf11d6134171db82e6ec67e2a813debd0a8de71cb685d2ebda669e31f");</script></html>
        '500':
          description: Internal Server Error
  /v1/api/payment/check-payment?invoice_code={invoice_code}:
    get:
      tags:
        - Web Payment SPIN
      summary: Check payment
      parameters: 
        - name: auth-key
          in: header
          required: true
          description: api-key value
          type: string
          example: dev_my_store_key
        - name: auth-token
          in: header
          required: true
          description: sha256(“||%%||” + api-key +“||%%||” + invoice_code + “||%%||” +api_gen_token +“||%%||”).hexdigest()
          type: string
          example: auth_token_abcdefghjiklmnopqrstuvwxyz1234567890
        - name: invoice_code
          in: path
          required: true
          description: invoice code transaction
          type: string
          example: MY_STORE_INVOICE
      produces: application/json
      responses:
        '200':
          description: OK
          content:
            success/json:
              schema:
                $ref: '#/components/schemas/ResponsCheckPayment'
        '500':
          description: Internal Server Error
  /v1/api/payment/reverse-payment?invoice_code={invoice_code}:
    get:
      tags:
        - Web Payment SPIN
      summary: Reverse payment
      parameters: 
        - name: auth-key
          in: header
          required: true
          description: api-key value
          type: string
          example: dev_my_store_key
        - name: auth-token
          in: header
          required: true
          description: sha256(“||%%||” + api-key +“||%%||” + invoice_code + “||%%||” +api_gen_token +“||%%||”).hexdigest()
          type: string
          example: auth_token_abcdefghjiklmnopqrstuvwxyz1234567890
        - name: invoice_code
          in: path
          required: true
          description: invoice code transaction
          type: string
          example: MY_STORE_INVOICE
      produces: application/json
      responses:
        '200':
          description: OK
          content:
            success/json:
              schema:
                $ref: '#/components/schemas/ResponsReversePayment'
        '500':
          description: Internal Server Error
  /v1/api/payment/cancel-payment?invoice_code={invoice_code}:
    get:
      tags:
        - Web Payment SPIN
      summary: Cancel payment
      parameters: 
        - name: auth-key
          in: header
          required: true
          description: api-key value
          type: string
          example: dev_my_store_key
        - name: auth-token
          in: header
          required: true
          description: sha256(“||%%||” + api-key +“||%%||” + invoice_code + “||%%||” +api_gen_token +“||%%||”).hexdigest()
          type: string
          example: auth_token_abcdefghjiklmnopqrstuvwxyz1234567890
        - name: invoice_code
          in: path
          required: true
          description: invoice code transaction
          type: string
          example: MY_STORE_INVOICE
      produces: application/json
      responses:
        '200':
          description: OK
          content:
            success/json:
              schema:
                $ref: '#/components/schemas/ResponsCancelPayment'
        '500':
          description: Internal Server Error
components:
  schemas:
    RequestToken:
      type: object
      properties:
        api_key:
          description: API Key (You can get the key and secret from SPIN Integration Team)
          type: string
          format: string
          example: dev_my_store_key
        api_secret:
          description: API Secret (You can get the key and secret from SPIN Integration Team)
          type: string
          format: string
          example: dev_secret_abcdefghjiklmnopqrstuvwxyz
    ResponsToken :
      type: object
      properties: 
        id:
          description: API_CALL
          type: string
          example: API_CALL_1586490272104432_5773512
        status_code:
          description: Will return the status based on code
          type: string
          example: 0000
        status :
          description: Will return the status as text SUCCESS
          type: string
          example: GET_API_GEN_TOKEN_SUCCESS
        desc:
          description: Will return a description of the status
          type: string
          example: GET_API_GEN_TOKEN_SUCCESS
        data:
          description: Will return url to process payment
          allOf: 
            - $ref: '#/components/schemas/Apigentoken'
            - type: object
    Apigentoken :
      type: object
      properties :
        api_gen_token:
          description: api_gen_token
          type: string
          example: 935e4e1b7cdc0657fce323e4865966031ceaef8169a695dc70b728a11e9e9f73
    ResponsTokenFailed :
      type: object
      properties:
        id:
          description: API_CALL
          type: string
          example: API_CALL_1234567890
        status_code:
          description: Will return the status based on code
          type: string
          example: 9999
        status:
          description: Will return the status as text FAILED
          type: string
          example: GET_API_KEY_FAILED
        desc:
          description: Will return a description of the status
          type: string
          example: ERROR CREATING KEY
        data:
          description: Will return url to process payment
          allOf:
            - $ref: '#/components/schemas/Apigentokenfailed'
            - type: object
    Apigentokenfailed :
      type: object
    RequestDoPayment : 
      type: object
      properties:
        amount:
          type: integer
          format: string
          description: Transaction Amount
          example: 20000
        wallet_id:
          type: string
          format: string
          description: SPIN Wallet ID
          example: 08121111111
        mid:
          type: string
          format: string
          description: SPIN Store Merchant ID
          example: dev_my_store_mid
        invoice_code:
          type: string
          format: string
          description: Mechant Invoice Unique ID
          example: MY_STORE_INVOICE
        content_type:
          type: string
          format: string
          required: false
          description: return JSON/HTML
          example: JSON
          enum:
            - JSON
            - HTML
        merchant_callback:
          type: string
          format: url
          description: Merchant Callback URL
          example: https://my.store.url
    ResponsDoPayment : 
      type: object
      properties: 
        id:
          description: API_CALL
          type: string
          example: API_CALL_1586490272104432_5773512
        status_code:
          description: Will return the status based on code
          type: string
          example: 0000
        status:
          description: Will return the status as text SUCCESS
          type: string
          example: DO_PAYMENT_SUCCESS
        desc:
          description: Will return a description of the status
          type: string
          example: DO_PAYMENT_SUCCESS
        data:
          description: Will return url to process payment
          allOf:
            - $ref: '#/components/schemas/Urldopayment'
            - type: object
    Urldopayment :
      type: object
      properties:
        url:
          description: url
          type: string
          example: https://dev-open-api-web-1.spinpay.id/console/view-payment-option?pay_session_trx=TRX_1586490272104432_6579559_780595_8077598&one_time_token=7470fdc9b918c06cf1d6590e20ae39be09f71e9326fafdea6fa23913e6d6418b
    ResponsCheckPayment :
      type: object
      properties: 
        id:
          description: API_CALL
          type: string
          example: API_CALL_1234567890
        status_code:
          description: Will return the status based on code
          type: string
          example: 0000
        status:
          description: Will return the status as text
          type: string
          example: CHECK_PAYMENT_SUCCESS
        desc:
          description: Will return a description of the status
          type: string
          example: CHECK PAYMENT SUCCESS
        data:
          description: Will return data check payment
          allOf:
            - $ref: '#/components/schemas/DataCheckPayment'
            - type: object
    DataCheckPayment :
      type: object
      properties: 
        wallet_id:
          description: SPIN Wallet ID
          type: integer
          example: 085748177755
        merchant_id:
          description: SPIN Store Merchant ID
          type: string
          example: 131431020311
        amount:
          description: Transaction Amount
          type: string
          example: 200000
        invoice_code:
          description: Mechant Invoice Unique ID
          type: string
          example: ivd105119111
        status_payment:
          description: number already registered
          type: string
          example: COMPLETED
        trx_id:
          description: The value returned from the transaction
          type: string
          example: 1586778128-11678
        pay_session_trx:
          description: the unique session of the transaction
          type: string
          example: TRX_158670906323313_2097471_628892_9888700
    ResponsReversePayment :
      type: object
      properties: 
        id:
          description: API_CALL
          type: string
          example: API_CALL_1234567890
        status_code:
          description: Will return the status based on code
          type: string
          example: 0000
        status:
          description: Will return the status as text
          type: string
          example: REVERSE_PAYMENT_SUCCESS
        desc:
          description: Will return a description of the status
          type: string
          example: REVERSE PAYMENT SUCCESS
        data:
          description: Will return data reverse payment
          allOf:
            - $ref: '#/components/schemas/DataReversePayment'
            - type: object
    DataReversePayment : 
      type: object
      properties:
        pay_session_trx:
          description: the unique session of the transaction
          type: string
          example: TRX_158670906323313_2097471_628892_9888700
        orig_trx_id:
          description: SPIN Wallet ID
          type: string
          example: 1584942583-11056
        trx_id:
          description: The value returned from the transaction
          type: string
          example: 1584943239-11057
        status_msg:
          description: Will return the status as text
          type: string
          example: ROLLBACK_SUCCESS
        invoice_code:
          description: Merchant Invoice Unique ID
          type: string
          example: ivd105119111
    ResponsCancelPayment :
      type: object
      properties: 
        id:
          description: API_CALL
          type: string
          example: API_CALL_1234567890
        status_code:
          description: Will return the status based on code
          type: string
          example: 0000
        status:
          description: Will return the status as text
          type: string
          example: CANCEL_PAYMENT_SUCCESS
        desc:
          description: Will return a description of the status
          type: string
          example: CANCEL_PAYMENT_SUCCESS
        data:
          description: Will return data cancel payment
          allOf:
            - $ref: '#/components/schemas/DataCancelPayment'
            - type: object
    DataCancelPayment : 
      type: object
      properties: 
        orig_pay_session_trx:
          description: the unique session of the transaction
          type: string
          example: TRX_1586779172185932_5306514_6043614_8703671
        invoice_code:
          description: Merchant Invoice Unique ID
          type: string
          example: ivd105119111